### ISSUE TITLE
:lady_beetle: The Desktop design is not properly placed

### ISSUE THREAD

**Issue by mahabubx7** [MussieTeka/Portfolio-Website#10]
### :lady_beetle: The desktop design is not properly placed
:heavy_multiplication_x: The Desktop design is not properly placed. 
I have attached the full desktop view of where the issue is occurring.
![image](https://user-images.githubusercontent.com/122348996/223350426-1ba36533-9cd0-45ad-9c25-c21080dc9a32.png)

**Comment by MussieTeka** [comment]
The issue was addressed and solved successfully.
