### ISSUE TITLE
Responsive website is not worked well..

### ISSUE THREAD

**Issue by fickryiman** [MussieTeka/Portfolio-Website#11]
- your design for the desktop version is awesome, it is very similar with figma design.
- button hover is not same one each others.
- otherwise responsive for mobile-version is not working well
![image](https://user-images.githubusercontent.com/116701353/223364339-102b361e-dfb3-4636-9d7e-2105a543a462.png)

**Comment by MussieTeka** [comment]
The issue was addressed and solved successfully.
